<?php

namespace Database\Seeders;

use App\Models\Faq;
use App\Models\SiteContent;
use Illuminate\Database\Seeder;

class CmsSeeder extends Seeder
{
    public function run(): void
    {
        $contents = [
            // ---- BERANDA: HERO ----
            ['beranda', 'hero', 'headline_1', 'string', 'Temukan'],
            ['beranda', 'hero', 'headline_1_color', 'string', '#FFFFFF'],
            ['beranda', 'hero', 'headline_2', 'string', 'karakter'],
            ['beranda', 'hero', 'headline_2_color', 'string', '#5CB2ED'],
            ['beranda', 'hero', 'headline_3', 'string', 'aromamu'],
            ['beranda', 'hero', 'headline_3_color', 'string', '#FFA3CB'],
            ['beranda', 'hero', 'headline_4', 'string', 'di Evomi'],
            ['beranda', 'hero', 'headline_4_color', 'string', '#FFFFFF'],
            ['beranda', 'hero', 'badge_left', 'string', 'Eau de Parfum'],
            ['beranda', 'hero', 'badge_left_icon', 'image', '/src/images/section 1/badge-left-star.svg'],
            ['beranda', 'hero', 'badge_right', 'string', 'Recycle Bottle Cap'],
            ['beranda', 'hero', 'badge_right_icon', 'image', '/src/images/section 1/recycle.png'],
            ['beranda', 'hero', 'product1_image', 'image', '/src/images/section 1/botol-purpose-prestige.png'],
            ['beranda', 'hero', 'product1_badge_label', 'string', 'Purpose Prestige'],
            ['beranda', 'hero', 'product1_badge_icon', 'image', '/src/images/section 1/purpose-prestige.png'],
            ['beranda', 'hero', 'product2_image', 'image', '/src/images/section 1/botol-rabel-brave.png'],
            ['beranda', 'hero', 'product2_badge_label', 'string', 'Rebel Brave'],
            ['beranda', 'hero', 'product2_badge_icon', 'image', '/src/images/section 1/rabel-brave.png'],
            ['beranda', 'hero', 'product3_image', 'image', '/src/images/section 1/botol-peaceful-calm.png'],
            ['beranda', 'hero', 'product3_badge_label', 'string', 'Peaceful Calm'],
            ['beranda', 'hero', 'product3_badge_icon', 'image', '/src/images/section 1/peaceful-calm.png'],
            ['beranda', 'hero', 'product4_image', 'image', '/src/images/section 1/botol-sweet-shy.png'],
            ['beranda', 'hero', 'product4_badge_label', 'string', 'Sweet Shy'],
            ['beranda', 'hero', 'product4_badge_icon', 'image', '/src/images/section 1/sweet-shy.png'],
            ['beranda', 'hero', 'marquee_text', 'string', 'Every Version of Me'],
            ['beranda', 'hero', 'divider_icon_1', 'image', '/src/images/section 1/purpose.png'],
            ['beranda', 'hero', 'divider_icon_2', 'image', '/src/images/section 1/peaceful.png'],
            ['beranda', 'hero', 'divider_icon_3', 'image', '/src/images/section 1/rab.png'],
            ['beranda', 'hero', 'divider_icon_4', 'image', '/src/images/section 1/sweetshy.png'],

            // ---- BERANDA: HERO STYLE (defaults = current layout) ----
            ['beranda', 'hero', 'headline_1_font_family', 'string', 'nohemi'],
            ['beranda', 'hero', 'headline_1_font_weight', 'string', '600'],
            ['beranda', 'hero', 'headline_1_font_style', 'string', 'normal'],
            ['beranda', 'hero', 'headline_1_fs_mobile', 'string', '28px'],
            ['beranda', 'hero', 'headline_1_fs_desktop', 'string', '42px'],
            ['beranda', 'hero', 'headline_2_font_family', 'string', 'nohemi'],
            ['beranda', 'hero', 'headline_2_font_weight', 'string', '600'],
            ['beranda', 'hero', 'headline_2_font_style', 'string', 'normal'],
            ['beranda', 'hero', 'headline_2_fs_mobile', 'string', '28px'],
            ['beranda', 'hero', 'headline_2_fs_desktop', 'string', '42px'],
            ['beranda', 'hero', 'headline_3_font_family', 'string', 'nohemi'],
            ['beranda', 'hero', 'headline_3_font_weight', 'string', '600'],
            ['beranda', 'hero', 'headline_3_font_style', 'string', 'normal'],
            ['beranda', 'hero', 'headline_3_fs_mobile', 'string', '28px'],
            ['beranda', 'hero', 'headline_3_fs_desktop', 'string', '42px'],
            ['beranda', 'hero', 'headline_4_font_family', 'string', 'nohemi'],
            ['beranda', 'hero', 'headline_4_font_weight', 'string', '600'],
            ['beranda', 'hero', 'headline_4_font_style', 'string', 'normal'],
            ['beranda', 'hero', 'headline_4_fs_mobile', 'string', '28px'],
            ['beranda', 'hero', 'headline_4_fs_desktop', 'string', '42px'],
            ['beranda', 'hero', 'headline_pos_top_mobile', 'string', '0px'],
            ['beranda', 'hero', 'headline_pos_top_desktop', 'string', '0px'],
            ['beranda', 'hero', 'headline_pos_left_mobile', 'string', '0px'],
            ['beranda', 'hero', 'headline_pos_left_desktop', 'string', '0px'],

            ['beranda', 'hero', 'badge_left_font_family', 'string', 'nohemi'],
            ['beranda', 'hero', 'badge_left_font_weight', 'string', '700'],
            ['beranda', 'hero', 'badge_left_font_style', 'string', 'normal'],
            ['beranda', 'hero', 'badge_left_fs_mobile', 'string', '7px'],
            ['beranda', 'hero', 'badge_left_fs_desktop', 'string', '14px'],
            ['beranda', 'hero', 'badge_left_icon_size_mobile', 'string', '8px'],
            ['beranda', 'hero', 'badge_left_icon_size_desktop', 'string', '20px'],
            ['beranda', 'hero', 'badge_left_left_mobile', 'string', '4%'],
            ['beranda', 'hero', 'badge_left_left_desktop', 'string', '9%'],
            ['beranda', 'hero', 'badge_left_top_mobile', 'string', '8%'],
            ['beranda', 'hero', 'badge_left_top_desktop', 'string', '5%'],

            ['beranda', 'hero', 'badge_right_font_family', 'string', 'nohemi'],
            ['beranda', 'hero', 'badge_right_font_weight', 'string', '700'],
            ['beranda', 'hero', 'badge_right_font_style', 'string', 'normal'],
            ['beranda', 'hero', 'badge_right_fs_mobile', 'string', '7px'],
            ['beranda', 'hero', 'badge_right_fs_desktop', 'string', '14px'],
            ['beranda', 'hero', 'badge_right_icon_size_mobile', 'string', '8px'],
            ['beranda', 'hero', 'badge_right_icon_size_desktop', 'string', '16px'],
            ['beranda', 'hero', 'badge_right_right_mobile', 'string', '-1%'],
            ['beranda', 'hero', 'badge_right_right_desktop', 'string', '4.7%'],
            ['beranda', 'hero', 'badge_right_bottom_mobile', 'string', '72%'],
            ['beranda', 'hero', 'badge_right_bottom_desktop', 'string', '80.4%'],

            // Hero wave SVGs (sayap)
            ['beranda', 'hero', 'wave_left_icon', 'image', '/src/images/section 1/sayap-kiri.svg'],
            ['beranda', 'hero', 'wave_right_icon', 'image', '/src/images/section 1/sayap-kanan.svg'],
            ['beranda', 'hero', 'wave_left_left_mobile', 'string', '-24%'],
            ['beranda', 'hero', 'wave_left_left_desktop', 'string', '-11%'],
            ['beranda', 'hero', 'wave_left_top_mobile', 'string', '-44%'],
            ['beranda', 'hero', 'wave_left_top_desktop', 'string', '-35%'],
            ['beranda', 'hero', 'wave_right_right_mobile', 'string', '-17%'],
            ['beranda', 'hero', 'wave_right_right_desktop', 'string', '-11%'],
            ['beranda', 'hero', 'wave_right_top_mobile', 'string', '-74%'],
            ['beranda', 'hero', 'wave_right_top_desktop', 'string', '-50%'],

            ['beranda', 'hero', 'product1_size_mobile', 'string', '100'],
            ['beranda', 'hero', 'product1_size_desktop', 'string', '100'],
            ['beranda', 'hero', 'product1_left_mobile', 'string', '7.7%'],
            ['beranda', 'hero', 'product1_left_desktop', 'string', '7.7%'],
            ['beranda', 'hero', 'product1_top_mobile', 'string', '-24.5%'],
            ['beranda', 'hero', 'product1_top_desktop', 'string', '-24.5%'],
            ['beranda', 'hero', 'product1_right_mobile', 'string', ''],
            ['beranda', 'hero', 'product1_right_desktop', 'string', ''],
            ['beranda', 'hero', 'product1_rotate_mobile', 'string', '3'],
            ['beranda', 'hero', 'product1_rotate_desktop', 'string', '3'],

            ['beranda', 'hero', 'product2_size_mobile', 'string', '100'],
            ['beranda', 'hero', 'product2_size_desktop', 'string', '100'],
            ['beranda', 'hero', 'product2_left_mobile', 'string', '-2.3%'],
            ['beranda', 'hero', 'product2_left_desktop', 'string', '-2.3%'],
            ['beranda', 'hero', 'product2_top_mobile', 'string', '-15%'],
            ['beranda', 'hero', 'product2_top_desktop', 'string', '-15%'],
            ['beranda', 'hero', 'product2_right_mobile', 'string', ''],
            ['beranda', 'hero', 'product2_right_desktop', 'string', ''],
            ['beranda', 'hero', 'product2_rotate_mobile', 'string', '-3'],
            ['beranda', 'hero', 'product2_rotate_desktop', 'string', '-3'],

            ['beranda', 'hero', 'product3_size_mobile', 'string', '100'],
            ['beranda', 'hero', 'product3_size_desktop', 'string', '100'],
            ['beranda', 'hero', 'product3_left_mobile', 'string', ''],
            ['beranda', 'hero', 'product3_left_desktop', 'string', ''],
            ['beranda', 'hero', 'product3_top_mobile', 'string', '-24%'],
            ['beranda', 'hero', 'product3_top_desktop', 'string', '-24%'],
            ['beranda', 'hero', 'product3_right_mobile', 'string', '13%'],
            ['beranda', 'hero', 'product3_right_desktop', 'string', '13%'],
            ['beranda', 'hero', 'product3_rotate_mobile', 'string', '4'],
            ['beranda', 'hero', 'product3_rotate_desktop', 'string', '4'],

            ['beranda', 'hero', 'product4_size_mobile', 'string', '100'],
            ['beranda', 'hero', 'product4_size_desktop', 'string', '100'],
            ['beranda', 'hero', 'product4_left_mobile', 'string', '-23.5%'],
            ['beranda', 'hero', 'product4_left_desktop', 'string', '-23.5%'],
            ['beranda', 'hero', 'product4_top_mobile', 'string', '-20%'],
            ['beranda', 'hero', 'product4_top_desktop', 'string', '-20%'],
            ['beranda', 'hero', 'product4_right_mobile', 'string', ''],
            ['beranda', 'hero', 'product4_right_desktop', 'string', ''],
            ['beranda', 'hero', 'product4_rotate_mobile', 'string', '-4'],
            ['beranda', 'hero', 'product4_rotate_desktop', 'string', '-4'],

            ['beranda', 'hero', 'marquee_font_family', 'string', 'nohemi'],
            ['beranda', 'hero', 'marquee_font_weight', 'string', '500'],
            ['beranda', 'hero', 'marquee_font_style', 'string', 'normal'],
            ['beranda', 'hero', 'marquee_fs_mobile', 'string', '8px'],
            ['beranda', 'hero', 'marquee_fs_desktop', 'string', '14px'],
            ['beranda', 'hero', 'divider_icon_1_size_mobile', 'string', '14px'],
            ['beranda', 'hero', 'divider_icon_1_size_desktop', 'string', '25px'],
            ['beranda', 'hero', 'divider_icon_2_size_mobile', 'string', '14px'],
            ['beranda', 'hero', 'divider_icon_2_size_desktop', 'string', '25px'],
            ['beranda', 'hero', 'divider_icon_3_size_mobile', 'string', '14px'],
            ['beranda', 'hero', 'divider_icon_3_size_desktop', 'string', '25px'],
            ['beranda', 'hero', 'divider_icon_4_size_mobile', 'string', '14px'],
            ['beranda', 'hero', 'divider_icon_4_size_desktop', 'string', '25px'],
            ['beranda', 'hero', 'divider_bottom_mobile', 'string', '8px'],
            ['beranda', 'hero', 'divider_bottom_desktop', 'string', '0px'],

            // ---- BERANDA: SECOND (characters) ----
            ['beranda', 'second', 'headline_1', 'string', 'Kenalan sama'],
            ['beranda', 'second', 'headline_2', 'string', 'karakter '],
            ['beranda', 'second', 'headline_3', 'string', 'kita yuk!'],
            ['beranda', 'second', 'card_icon_size_mobile', 'string', '100px'],
            ['beranda', 'second', 'card_icon_size_desktop', 'string', '140px'],
            ['beranda', 'second', 'card_label_gap_mobile', 'string', '0px'],
            ['beranda', 'second', 'card_label_gap_desktop', 'string', '12px'],
            ['beranda', 'second', 'card_gap_horizontal_mobile', 'string', '16px'],
            ['beranda', 'second', 'card_gap_horizontal_desktop', 'string', '32px'],
            ['beranda', 'second', 'cta_label', 'string', 'Lihat Semua Karakter'],
            ['beranda', 'second', 'card1_name', 'string', "Purpose\nPrestige"],
            ['beranda', 'second', 'card1_title', 'string', 'Purpose Prestige'],
            ['beranda', 'second', 'card1_image', 'image', '/src/images/section 2/purpose-prestige.png'],
            ['beranda', 'second', 'card2_name', 'string', "Peaceful\nCalm"],
            ['beranda', 'second', 'card2_title', 'string', 'Peaceful Calm'],
            ['beranda', 'second', 'card2_image', 'image', '/src/images/section 2/peaceful-calm.png'],
            ['beranda', 'second', 'card3_name', 'string', "Rabel\nBrave"],
            ['beranda', 'second', 'card3_title', 'string', 'Rebel Brave'],
            ['beranda', 'second', 'card3_image', 'image', '/src/images/section 2/rabel-brave.png'],
            ['beranda', 'second', 'card4_name', 'string', "Sweet\nShy"],
            ['beranda', 'second', 'card4_title', 'string', 'Sweet Shy'],
            ['beranda', 'second', 'card4_image', 'image', '/src/images/section 2/sweet-shy.png'],

            // ---- BERANDA: THIRD ----
            ['beranda', 'third', 'card1_title', 'string', "Self\nAwareness"],
            ['beranda', 'third', 'card1_desc', 'text', 'Setiap aroma dirancang untuk merepresentasikan versi diri, emosi, dan karakter manusia yang berbeda, sehingga parfum menjadi medium ekspresi personal, bukan sekadar wewangian.'],
            ['beranda', 'third', 'card1_icon', 'image', '/src/images/section 3/star-medium.png'],
            ['beranda', 'third', 'card2_title', 'string', "Environment\nFriendly"],
            ['beranda', 'third', 'card2_desc', 'text', 'Mengusung kepedulian terhadap lingkungan melalui pemanfaatan daur ulang tutup botol plastik menjadi bagian dari identitas produk, sebagai bentuk kontribusi kecil dalam mengurangi limbah plastik sekaligus menghadirkan nilai sustainability.'],
            ['beranda', 'third', 'card2_icon', 'image', '/src/images/section 3/peaceful-calm.png'],
            ['beranda', 'third', 'card3_title', 'string', "Playful Design\nConcept"],
            ['beranda', 'third', 'card3_desc', 'text', 'Dikemas dengan pendekatan visual yang playful, ekspresif, dan dekat dengan generasi muda agar pengalaman menggunakan parfum terasa lebih personal dan menyenangkan.'],
            ['beranda', 'third', 'card3_icon', 'image', '/src/images/section 3/triangle.png'],

            // ---- BERANDA: FOURTH ----
            ['beranda', 'fourth', 'image', 'image', '/src/images/section 4/thanks-card.png'],

            // ---- BERANDA: FIFTH ----
            ['beranda', 'fifth', 'card1_title', 'string', 'Purpose Prestige'],
            ['beranda', 'fifth', 'card1_badge', 'string', 'Optimis'],
            ['beranda', 'fifth', 'card1_desc', 'text', 'Aroma yang merefleksikan ketenangan dan kejelasan tujuan.'],
            ['beranda', 'fifth', 'card1_price', 'string', 'Rp189.000'],
            ['beranda', 'fifth', 'card1_image', 'image', '/src/images/section 5/purpose-prestige.png'],
            ['beranda', 'fifth', 'card2_title', 'string', 'Peaceful Calm'],
            ['beranda', 'fifth', 'card2_badge', 'string', 'Damai'],
            ['beranda', 'fifth', 'card2_desc', 'text', 'Aroma menenangkan yang menyatu dengan diri.'],
            ['beranda', 'fifth', 'card2_price', 'string', 'Rp199.000'],
            ['beranda', 'fifth', 'card2_image', 'image', '/src/images/section 5/peaceful-calm.png'],
            ['beranda', 'fifth', 'card3_title', 'string', 'Rebel Brave'],
            ['beranda', 'fifth', 'card3_badge', 'string', 'Berani'],
            ['beranda', 'fifth', 'card3_desc', 'text', 'Keberanian dan semangat untuk mengekspresikan diri.'],
            ['beranda', 'fifth', 'card3_price', 'string', 'Rp179.000'],
            ['beranda', 'fifth', 'card3_image', 'image', '/src/images/section 5/rabel-brave.png'],
            ['beranda', 'fifth', 'card4_title', 'string', 'Sweet Shy'],
            ['beranda', 'fifth', 'card4_badge', 'string', 'Manis'],
            ['beranda', 'fifth', 'card4_desc', 'text', 'Aroma menenangkan yang menyatu dengan diri.'],
            ['beranda', 'fifth', 'card4_price', 'string', 'Rp189.000'],
            ['beranda', 'fifth', 'card4_image', 'image', '/src/images/section 5/sweet-shy.png'],

            // ---- BERANDA: SIXTH ----
            ['beranda', 'sixth', 'title_1', 'string', 'Packaging'],
            ['beranda', 'sixth', 'title_2', 'string', 'Reveal'],
            ['beranda', 'sixth', 'image', 'image', '/src/images/section 6/packaging.png'],
            ['beranda', 'sixth', 'label1', 'string', "Purpose\nPrestige"],
            ['beranda', 'sixth', 'label2', 'string', "Rebel\nBrave"],
            ['beranda', 'sixth', 'label3', 'string', "Peaceful\nCalm"],
            ['beranda', 'sixth', 'label4', 'string', "Sweet\nShy"],

            // ---- BERANDA: SEVENTH ----
            ['beranda', 'seventh', 'headline_1', 'string', 'Temukan'],
            ['beranda', 'seventh', 'headline_2', 'string', 'aromamu'],
            ['beranda', 'seventh', 'headline_3', 'string', 'dengan'],
            ['beranda', 'seventh', 'headline_4', 'string', 'bermain'],
            ['beranda', 'seventh', 'headline_5', 'string', 'kuis'],
            ['beranda', 'seventh', 'cta_label', 'string', 'Mulai Kuis'],
            ['beranda', 'seventh', 'product_image', 'image', '/src/images/section 7/produk.png'],

            // Section 7 — 4 product labels (1 Prestige, 2 Calm, 3 Rebel, 4 Sweet)
            ['beranda', 'seventh', 'label1_text', 'string', 'Prestige'],
            ['beranda', 'seventh', 'label1_title', 'string', 'Purpose Prestige'],
            ['beranda', 'seventh', 'label1_color', 'string', '#5CB2ED'],
            ['beranda', 'seventh', 'label1_fs_mobile', 'string', '9px'],
            ['beranda', 'seventh', 'label1_fs_desktop', 'string', '16px'],
            ['beranda', 'seventh', 'label1_left_mobile', 'string', '61%'],
            ['beranda', 'seventh', 'label1_left_desktop', 'string', '61%'],
            ['beranda', 'seventh', 'label1_right_mobile', 'string', ''],
            ['beranda', 'seventh', 'label1_right_desktop', 'string', ''],
            ['beranda', 'seventh', 'label1_top_mobile', 'string', '33%'],
            ['beranda', 'seventh', 'label1_top_desktop', 'string', '33%'],
            ['beranda', 'seventh', 'label1_bottom_mobile', 'string', ''],
            ['beranda', 'seventh', 'label1_bottom_desktop', 'string', ''],

            ['beranda', 'seventh', 'label2_text', 'string', 'Calm'],
            ['beranda', 'seventh', 'label2_title', 'string', 'Peaceful Calm'],
            ['beranda', 'seventh', 'label2_color', 'string', '#5EA14A'],
            ['beranda', 'seventh', 'label2_fs_mobile', 'string', '9px'],
            ['beranda', 'seventh', 'label2_fs_desktop', 'string', '16px'],
            ['beranda', 'seventh', 'label2_left_mobile', 'string', '82%'],
            ['beranda', 'seventh', 'label2_left_desktop', 'string', '82%'],
            ['beranda', 'seventh', 'label2_right_mobile', 'string', ''],
            ['beranda', 'seventh', 'label2_right_desktop', 'string', ''],
            ['beranda', 'seventh', 'label2_top_mobile', 'string', '15%'],
            ['beranda', 'seventh', 'label2_top_desktop', 'string', '15%'],
            ['beranda', 'seventh', 'label2_bottom_mobile', 'string', ''],
            ['beranda', 'seventh', 'label2_bottom_desktop', 'string', ''],

            ['beranda', 'seventh', 'label3_text', 'string', 'Rebel'],
            ['beranda', 'seventh', 'label3_title', 'string', 'Rebel Brave'],
            ['beranda', 'seventh', 'label3_color', 'string', '#E33D35'],
            ['beranda', 'seventh', 'label3_fs_mobile', 'string', '9px'],
            ['beranda', 'seventh', 'label3_fs_desktop', 'string', '16px'],
            ['beranda', 'seventh', 'label3_left_mobile', 'string', '26%'],
            ['beranda', 'seventh', 'label3_left_desktop', 'string', '26%'],
            ['beranda', 'seventh', 'label3_right_mobile', 'string', ''],
            ['beranda', 'seventh', 'label3_right_desktop', 'string', ''],
            ['beranda', 'seventh', 'label3_top_mobile', 'string', '15%'],
            ['beranda', 'seventh', 'label3_top_desktop', 'string', '15%'],
            ['beranda', 'seventh', 'label3_bottom_mobile', 'string', ''],
            ['beranda', 'seventh', 'label3_bottom_desktop', 'string', ''],

            ['beranda', 'seventh', 'label4_text', 'string', 'Sweet'],
            ['beranda', 'seventh', 'label4_title', 'string', 'Sweet Shy'],
            ['beranda', 'seventh', 'label4_color', 'string', '#DD74A5'],
            ['beranda', 'seventh', 'label4_fs_mobile', 'string', '9px'],
            ['beranda', 'seventh', 'label4_fs_desktop', 'string', '16px'],
            ['beranda', 'seventh', 'label4_left_mobile', 'string', '47.5%'],
            ['beranda', 'seventh', 'label4_left_desktop', 'string', '47.5%'],
            ['beranda', 'seventh', 'label4_right_mobile', 'string', ''],
            ['beranda', 'seventh', 'label4_right_desktop', 'string', ''],
            ['beranda', 'seventh', 'label4_top_mobile', 'string', '-3%'],
            ['beranda', 'seventh', 'label4_top_desktop', 'string', '-3%'],
            ['beranda', 'seventh', 'label4_bottom_mobile', 'string', ''],
            ['beranda', 'seventh', 'label4_bottom_desktop', 'string', ''],

            // ---- KONTAK ----
            ['kontak', 'header', 'title', 'string', 'Hubungi Kami'],
            ['kontak', 'header', 'subtitle', 'text', 'Punya pertanyaan atau ingin berkolaborasi? Tim Evomi siap mendengarkan Anda.'],
            ['kontak', 'info', 'email_label', 'string', 'Email'],
            ['kontak', 'info', 'email_value', 'string', 'hello@evomi.id'],
            ['kontak', 'info', 'phone_label', 'string', 'WhatsApp'],
            ['kontak', 'info', 'phone_value', 'string', '+62 812-3456-7890'],
            ['kontak', 'info', 'address_label', 'string', 'Kantor Pusat'],
            ['kontak', 'info', 'address_value', 'string', 'Jakarta, Indonesia'],

            // ---- NAVBAR ----
            ['navbar', 'site', 'browser_title', 'string', 'Evomi Website'],
            ['navbar', 'site', 'dashboard_browser_title', 'string', 'Evomi Dashboard'],
            ['navbar', 'site', 'favicon', 'image', '/favicon.ico'],
            ['navbar', 'menu', 'beranda', 'string', 'Beranda'],
            ['navbar', 'menu', 'tentang', 'string', 'Tentang'],
            ['navbar', 'menu', 'belanja', 'string', 'Belanja'],
            ['navbar', 'menu', 'artikel', 'string', 'Artikel'],
            ['navbar', 'menu', 'kuis', 'string', 'Kuis'],
            ['navbar', 'menu', 'login', 'string', 'Login'],
            ['navbar', 'menu', 'register', 'string', 'Daftar'],
            ['navbar', 'menu', 'logout', 'string', 'Logout'],

            // ---- FOOTER ----
            ['footer', 'bulletin', 'title', 'string', 'Buletin Evomi'],
            ['footer', 'bulletin', 'desc', 'text', 'Daftar untuk menerima koleksi terbaru, penawaran eksklusif, dan cerita tentang setiap karakter aroma.'],
            ['footer', 'bulletin', 'cta', 'string', 'Daftar'],
            ['footer', 'menu', 'heading', 'string', 'Menu'],
            ['footer', 'menu', 'beranda', 'string', 'Beranda'],
            ['footer', 'menu', 'belanja', 'string', 'Belanja'],
            ['footer', 'menu', 'kuis', 'string', 'Kuis'],
            ['footer', 'help', 'heading', 'string', 'Bantuan'],
            ['footer', 'help', 'faq', 'string', 'FAQ'],
            ['footer', 'help', 'pengiriman', 'string', 'Status Pengiriman'],
            ['footer', 'help', 'kontak', 'string', 'Kontak'],
            ['footer', 'social', 'heading', 'string', 'Ikuti Kami'],
            ['footer', 'social', 'instagram_url', 'string', 'https://instagram.com/evomi.id'],
            ['footer', 'social', 'twitter_url', 'string', 'https://twitter.com/evomi'],
            ['footer', 'social', 'facebook_url', 'string', 'https://facebook.com/evomi'],
            ['footer', 'legal', 'copyright', 'string', '© Evomi. All rights reserved.'],
        ];

        foreach ($contents as [$page, $section, $key, $type, $value]) {
            SiteContent::firstOrCreate(
                ['page' => $page, 'section' => $section, 'key' => $key, 'locale' => 'id'],
                ['type' => $type, 'value' => $value]
            );
        }

        $faqs = [
            [
                'Pesanan & Pembayaran',
                'Orders & Payment',
                'Bagaimana cara melacak pesanan saya?',
                'How can I track my order?',
                "Setelah pesanan diproses, Anda akan menerima email konfirmasi dengan nomor pelacakan yang dapat dipantau di halaman 'Status Pesanan'.",
                "After your order is processed, you will receive a confirmation email with a tracking number that you can monitor on the 'Order Status' page.",
                1,
            ],
            [
                'Pesanan & Pembayaran',
                'Orders & Payment',
                'Metode pembayaran apa yang tersedia?',
                'What payment methods are available?',
                'Kami menerima berbagai metode pembayaran termasuk transfer bank, e-wallet (GoPay, OVO, Dana), dan kartu kredit.',
                'We accept various payment methods including bank transfer, e-wallets (GoPay, OVO, Dana), and credit cards.',
                2,
            ],
            [
                'Pengiriman & Retur',
                'Shipping & Returns',
                'Berapa lama estimasi pengiriman?',
                'How long does shipping take?',
                'Pengiriman reguler memakan waktu 2-4 hari kerja. Kami juga menyediakan opsi pengiriman instan untuk wilayah Jabodetabek.',
                'Regular shipping takes 2–4 business days. We also offer instant shipping for the Greater Jakarta area.',
                3,
            ],
            [
                'Pengiriman & Retur',
                'Shipping & Returns',
                'Bisakah saya mengembalikan produk?',
                'Can I return a product?',
                'Kami menerima retur jika produk rusak saat diterima. Pastikan untuk melampirkan video unboxing sebagai syarat klaim.',
                'We accept returns if the product is damaged upon arrival. Please attach an unboxing video as a claim requirement.',
                4,
            ],
            [
                'Tentang Aroma',
                'About the Scents',
                'Apakah parfum Evomi aman untuk kulit?',
                'Is Evomi perfume safe for the skin?',
                'Ya, setiap racikan parfum Evomi menggunakan bahan-bahan yang telah tersertifikasi aman untuk kulit.',
                'Yes, every Evomi fragrance blend uses ingredients certified as skin-safe.',
                5,
            ],
            [
                'Tentang Aroma',
                'About the Scents',
                'Bagaimana cara memilih aroma yang tepat?',
                'How do I choose the right scent?',
                'Anda dapat mencoba Kuis Persona kami di halaman utama untuk mendapatkan rekomendasi aroma berdasarkan kepribadian Anda.',
                'You can try our Persona Quiz on the home page to get scent recommendations based on your personality.',
                6,
            ],
        ];

        foreach ($faqs as [$category, $categoryEn, $question, $questionEn, $answer, $answerEn, $sort]) {
            Faq::updateOrCreate(
                ['question' => $question],
                [
                    'category' => $category,
                    'category_en' => $categoryEn,
                    'question_en' => $questionEn,
                    'answer' => $answer,
                    'answer_en' => $answerEn,
                    'sort_order' => $sort,
                    'is_active' => true,
                ]
            );
        }
    }
}
